AWSTemplateFormatVersion: 2010-09-09
Description: Academy CloudFormation Exercise
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 1000
Outputs:
  WebsiteURL:
    Value: !GetAtt
      - S3Bucket
      - WebsiteURL
    Description: URL for website hosted on S3